version: '3.7'
services:
  dfotose:
    container_name: dfotose
    restart: unless-stopped
    build: .
    ports:
      - 127.0.0.1:4000:4000
    volumes:
      - ./storage:/dfotose/storage
      - ./uploaded-images:/dfotose/uploaded-images
      - ./src:/dfotose/src
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  redis:
    container_name: dfotose-redis
    image: "redis:alpine"
    restart: unless-stopped
  mongo:
    container_name: dfotose-mongodb
    restart: unless-stopped
    image: "mongo:4.0.1"
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles
